[project]
name = "test-mcp"
version = "0.1.0"
description = "Simple MCP server for testing purposes."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.6.0",
    "pyside6>=6.9.0",
    "requests>=2.32.3",
]
