[project]
name = "test-mcp"
version = "1.0.0"
description = "Simple MCP server for testing purposes."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.12.2",
    "requests>=2.32.3",
    "pyside6>=6.9.0", # Only needed for simple_ui.py
]
